### ISSUE TITLE
Does the sdlc of cwc coming to an end  ? 

### ISSUE THREAD

**Issue by skyerjoe** [mh-/corona-warn-companion-android#132]
Hello everyone, 

I want to ask the dev. if the cwc development line is finished.
Don't get me wrong @mh- creates a great addon for cctg/cwa and brings encounter detection on a new level without rooting. 
 
If not, may it's possible to enhance sth. like several additional infos to the risk level calculation diagram. 

If it's still ended , thnx for ur great work and wish u all the best 

Best regards

**Comment by mh-** [comment]
For some time, the use of this app seemed to decline (measured by the amount of feedback I received, since of course there is no tracking in the app), and it didn't seem to make much sense to change anything.

Some weeks ago however, I started to receive messages from users again; because of the increase in COVID-19 infection numbers, people seem to become more interested in this app again.

So: no, development is not finished, feel free to suggest improvements. 

However, note that the app is deployed in many countries, so it's difficult to give correct information for all local variants. 
It is also not the intention of the app to give risk advice, this would conflict with Google Play Store rules. The risk assessment can only be done by the country's official app, like CWA in Germany. 
Users can use this app to get more info on when the encounter happened, so that they maybe can remember whether they wore a mask, etc.

**Comment by mh-** [comment]
Also, please feel free to implement improvements yourself and submit Pull Requests.

**Comment by skyerjoe** [comment]
Unfortunately im not a dev.
I could rudimentary read java but thats it.

But i can help u whilst  reproduce some error and create some strace logs.
