### ISSUE TITLE
Better use CCTG Export Mode (CWC somehow "removes" RPI data in root mode from CCTG)

### ISSUE THREAD

**Issue by citizenserious** [mh-/corona-warn-companion-android#141]
There seems to be a problem with ID loss of CCTG after using CWC [CCTG Mode (root)].
The issue was first discussed here:
https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/72

**Comment by mh-** [comment]
For this use case I would recommend to not use the root mode, but rather export data from CCTG, i.e. share contact data from the encounters tab of the CCTG to CWC. 
Because CCTG offers this export option, there's no need for the root tricks that apparently do not always work reliably.

**Comment by skyerjoe** [comment]
Is this commited in 2.1.3 ?

**Comment by KaratekHD** [comment]
I am not quite sure  why the root  mode messes up the database for CCTG and not for CWA. 
I will try to debug this as soon as I have some free time.
One possibility I could imagine would be that the error happens when the database gets copied while CCTG is using it, so I'll try to see whether I can  automate something like
1. Let  CWC close CCTG
2. Copy the database
3. Relaunch  CCTG  in the background
I don't know whether this will work or is plausible, we'll see.
@mh- Could you maybe assign this to me?

**Comment by mh-** [comment]
Should be solved with https://github.com/mh-/corona-warn-companion-android/commit/5db7b75f78fc4101cc07347d42e66c2d50892f48
