### ISSUE TITLE
Double warnings with Austrian DK enabled?

### ISSUE THREAD

**Issue by hman2** [mh-/corona-warn-companion-android#145]
The new release of Companion now deals better with large data, thanks for that (currently: 1100 RPIs collected and 2,5 million diagnosis keys).

Therefore I re-enabled processing Austrian diagnosis keys (the previous version crashed with Austrian keys). With enabling Austrian keys, all of the three days where I currently have warnings (-85 dB to -100 dB signals, so no real concerns - despite the fact that one of the risks of transfer is being labelled "red", not using a number - reason unknown) the reported risks have doubled.

And on any of those days all those doubled risks allegedly occurred at exactly (!) the same time. That is hard to believe, so I guess that either Austrian DK are mirrored in German or vice versa, or Companion doubles these...

Thanks for inspecting.

**Comment by mh-** [comment]
Yes, the data is shared between countries, see e.g. https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/travel-during-coronavirus-pandemic/how-tracing-and-warning-apps-can-help-during-pandemic_en 
Thus it doesn't make sense to activate both "Germany + x" and "Austria", because the "+ x" includes Austria. (And Austria likely includes Germany as well?)

**Comment by hman2** [comment]
Thanks. In that case, you should IMHO update the flags shown when standard Germany is activated...

**Comment by mh-** [comment]
https://github.com/mh-/corona-warn-companion-android/commit/0c9e68f623334f7d11261d18034ee9f04e9b198a
