### ISSUE TITLE
Alternatives for non-rooted devices

### ISSUE THREAD

**Issue by mhellmeier** [mh-/corona-warn-companion-android#42]
Are there any possibilities for non-rooted devices to use the app with already existing records?

I know about the _RaMBLE mode_ but this seems to work only on newly recorded data, not on old already traced contacts.

In the Android location settings it is possible to switch to the "COVID-19-Benachrichtigungen" and export information about the "Überprüfung auf mögliche Begegnungen". I know that these export doesn't include information about the attenuation in dB but perhaps in can be used to display some more insights than the official apps do!?

**Comment by mh-** [comment]
You can have these exports parsed using https://felixlen.github.io/ena_log/ - but I'm afraid you will not gain many insights from these exports.

The database that stores the scanned RPIs is stored in the Android file system at `/data/data/com.google.android.gms/app_contact-tracing-contact-record-db/` - and this location is protected from access by other apps, that's why you need to root the device.
