### ISSUE TITLE
[question] raw RSSI vs calibrated RSSI 

### ISSUE THREAD

**Issue by skyerjoe** [mh-/corona-warn-companion-android#87]
Could u describe the differences from both in an easy way and what's does it mean to use it in the app causeunfortunately im not an android dev

Thanks in advance and 

good job with the extension  keep going

**Comment by mh-** [comment]
It's all explained [here](https://developers.google.com/android/exposure-notifications/ble-attenuation-overview), and a more simple explanation would be:

Each phone type has a different Bluetooth antenna, different chips, and so on, and therefore will come up with a different measurement for the RSSI (received signal strength indication). This RSSI is used to estimate how far away the other phone was during the encounter.
Because each phone is different, Google tries to measure reference values for some popular phones.
They have a table with calibration values: https://developers.google.com/android/exposure-notifications/files/en-calibration-2020-08-12.csv
The Google framework uses this table to add an `RSSI_correction` value.
My app does not.

**Comment by skyerjoe** [comment]
Hello @mh- 

Thnks for reply 

But what does this mean for using with the Ramble Scanner ? 
Are the results far away from reality related to the root method  ? 
are there any testings possibe with ur app to proof against the root one ? 

or is these topic too complex to address 

best regards

**Comment by mh-** [comment]
ur device in that list?

**Comment by skyerjoe** [comment]
My Device is  Xiaomi: Mi9T pro 128 GB

I think this is the right entry : 
xiaomi | raphael | Mi 9T Pro | 1 | -23 | 1

 | -- | -- | -- | -- | --

best regards

**Comment by mh-** [comment]
```
manufacturer, device,  model,     rssi correction, tx,  calibration confidence
xiaomi,       raphael, Mi 9T Pro, 1,               -23, 1
```
--> so `RSSI_correction` is 1.
The formula is `Attenuation = TX_power - (RSSI_measured + RSSI_correction)`,
this means that the original Corona-Warn-App will calculate with an attenuation that is 
**1**dB lower than the value that Warn-App-Companion shows.

This is very close. The color that Warn-App-Companion chooses for the displayed dots will most likely be the "correct" colors.

**Comment by skyerjoe** [comment]
sounds good and practicable for me to still use the combi Companion and Ramble.

btw. am i able to donate for ur work in any way ( paypal or bitcoin will be the best bets ) ? 

best regards

**Comment by skyerjoe** [comment]
additional question: 

if i use cwca with Ramble i dont need cwa anymore or ? 

best regards

**Comment by mh-** [comment]
@skyerjoe This app does not aim to replace CWA. 
CWA will automatically warn you, and it will allow you to warn others. 
This app may have problems and may be unreliable, and it will not run automatically, so I strongly recommend to keep using CWA, and use CWA to warn others, should you ever be infected.

**Comment by skyerjoe** [comment]
ok ure right my sight was to narrow 
so the best is to use both simultanously or  root and get rid of Rambler.
may i will think about...  

best regards
